function insertar(){
				$.ajax({
				  url: "insertar.php",
				  data: {pro_linea : $("#pro_linea").val(),
						pro_region : $("#pro_region").val(),
						pro_centro : $("#pro_centro").val(),
						nom_sub: $("#nom_sub").val(),
						ema_sub: $("#ema_sub").val(),
						num_cel_sub: $("#num_cel_sub").val(),
						pro_autores: $("#pro_autores").val(),
						nom_rad_pro: $("#nom_rad_pro").val(),
						num_identi: $("#num_identi").val(),
						ema_rad_pro: $("#ema_rad_pro").val(),
						Cel_rad_pro: $("#Cel_rad_pro").val(),
						titulo_pro: $("#titulo_pro").val(),
						area_con_1: $("#area_con_1").val(),
						area_con_2: $("#area_con_2").val(),
						apli_posconf: $("#apli_posconf").val(),
						muni_impact: $("#muni_impact").val(),
						des_estra: $("#des_estra").val(),
						recu_poscof: $("#recu_poscof").val(),
						ante_just_pro: $("#ante_just_pro").val(),
						plan_pro_nec: $("#plan_pro_nec").val(),
						obj_general: $("#obj_general").val(),
						obj_esp1: $("#obj_esp1").val(),
						obj_esp2: $("#obj_esp2").val(),
						obj_esp3: $("#obj_esp3").val(),
						obj_esp4: $("#obj_esp4").val(),
						fech_ini_pro: $("#fech_ini_pro").val(),
						fech_fin_pro: $("#fech_fin_pro").val(),
						nom_gru_inv: $("#nom_gru_inv").val(),
						cod_grupo: $("#cod_grupo").val(),
						num_sem_bene: $("#num_sem_bene").val(),
						nomb_sem_bene: $("#nomb_sem_bene").val(),
						des_meto_pro: $("#des_meto_pro").val(),
						resu_obj_esp1: $("#resu_obj_esp1").val(),
						resu_obj_esp2: $("#resu_obj_esp2").val(),
						resu_obj_esp3: $("#resu_obj_esp3").val(),
						resu_obj_esp4: $("#resu_obj_esp4").val(),
						prod_resu_1: $("#prod_resu_1").val(),
						prod_resu_2: $("#prod_resu_2").val(),
						prod_resu_3: $("#prod_resu_3").val(),
						prod_resu_4: $("#prod_resu_4").val(),
						num_pro_bene: $("#num_pro_bene").val(),
						nom_pro_bene: $("#nom_pro_bene").val(),
						imp_esperado: $("#imp_esperado").val(),
						num_per_ext: $("#num_per_ext").val(),
						nom_apr_ext: $("#nom_apr_ext").val(),
						num_iden_ext: $("#num_iden_ext").val(),
						num_pers_int_s: $("#num_pers_int_s").val(),
						nom_ape_int_s: $("#nom_ape_int_s").val(),
						num_iden_int_s: $("#num_iden_int_s").val(),
						num_pers_int_c: $("#num_pers_int_c").val(),
						num_pers_int_cm: $("#num_pers_int_cm").val(),
						num_pers_int_in:$("#num_pers_int_in").val(),
						nom_apellidos: $("#nom_apellidos").val(),
						num_idenficac: $("#num_idenficac").val(),
						num_per_int_s: $("#num_per_int_s").val(),
						nom_apell_pers: $("#nom_apell_pers").val(),
						num_iden_pers: $("#num_iden_pers").val(),
						nom_ali_int: $("#nom_ali_int").val(),
						nit: $("#nit").val(),
						rec_esp_ent_ext: $("#rec_esp_ent_ext").val(),
						rec_din_ent_ext: $("#rec_din_ent_ext").val(),
						rec_esp_ent_int: $("#rec_esp_ent_int").val(),
						rec_din_ent_int: $("#rec_din_ent_int").val(),
						cui_mun_inf: $("#cui_mun_inf").val(),
						des_ali_obj: $("#des_ali_obj").val(),
						ot_se_pe_in: $("#ot_se_pe_in").val(),
						descripcion1: $("#descripcion1").val(),
						se_pe_in: $("#se_pe_in").val(),
						descripcion2: $("#descripcion2").val(),
						eq_de_si: $("#eq_de_si").val(),
						descripcion3: $("#descripcion3").val(),
						sofware: $("#sofware").val(),
						descripcion4: $("#descripcion4").val(),
						maq_ind: $("#maq_ind").val(),
						descripcion5: $("#descripcion5").val(),
						otr_com_equi: $("#otr_com_equi").val(),
						descripcion6: $("#descripcion6").val(),
						ma_pa_for: $("#ma_pa_for").val(),
						descripcion7: $("#descripcion7").val(),
						man_maq_equ: $("#man_maq_equ").val(),
						descripcion8: $("#descripcion8").val(),
						ot_com_tra: $("#ot_com_tra").val(),
						descripcion9: $("#descripcion9").val(),
						ot_gast_imp: $("#ot_gast_imp").val(),
						descripcion10: $("#descripcion10").val(),
						div_act: $("#div_act").val(),
						descripcion11: $("#descripcion11").val(),
						via_gast_int: $("#via_gast_int").val(),
						descripcion12: $("#descripcion12").val(),
						gast_bien: $("#gast_bien").val(),
						descripcion13: $("#descripcion13").val(),
						ade_cons: $("#ade_cons").val(),
						descripcion14: $("#descripcion14").val(),
						monitores: $("#monitores").val(),
						descripcion15: $("#descripcion15").val()},
				  type: "POST",
				  
				  success: function(response){
				          alert(response);
						  
					}
				  
				});
			}